all: select.cgi select2.cgi login.cgi main.cgi food.cgi walking.cgi ball.cgi pet.cgi

select.cgi: select.c
	comelang2 -o select.cgi select.c

select2.cgi: select2.c
	comelang2 -o select2.cgi select2.c

login.cgi: login.c
	comelang2 -o login.cgi login.c

main.cgi: main.c
	comelang2 -o main.cgi main.c

food.cgi: food.c
	comelang2 -o food.cgi food.c

walking.cgi: walking.c
	comelang2 -o walking.cgi walking.c

ball.cgi: ball.c
	comelang2 -o ball.cgi ball.c

pet.cgi: pet.c
	comelang2 -o pet.cgi pet.c

clean:
	rm -f *.cgi
